### ISSUE TITLE
Indentation beep broken when using enhance tones process in NVDA 023.1

### ISSUE THREAD

**Issue by tmthywynn8** [davidacm/enhancedTones#1]
## STR:

1. In NVDA's document formatting settings, make sure line indentation reporting is set to tones and enhanced tones add-on is enabled.
2. Open Notepad.
3. Press *Tab* and review the current line, e.g., press *up arrow*.

Expected: A beep should be generated.

Actual:
```
IO - speech.speech.speak (10:45:00.007) - MainThread (8872):
Speaking ['Log fragment start position marked, press again to copy to clipboard']
IO - inputCore.executeGesture (10:45:01.963) - winInputHook (8284):
Input: kb(laptop):downArrow
DEBUG - editableText.EditableText._hasCaretMoved (10:45:02.001) - MainThread (8872):
Caret move detected using event. Elapsed: 0 ms
IO - speech.speech.speak (10:45:02.003) - MainThread (8872):
Speaking [BeepCommand(246.94165062806206, 80, left=50, right=50), 'blank']
ERROR - speech.manager.SpeechManager._handleIndex (10:45:02.010) - MainThread (8872):
Error running speech callback
Traceback (most recent call last):
  File "speech\manager.pyc", line 685, in _handleIndex
  File "speech\commands.pyc", line 360, in run
TypeError: beep() got an unexpected keyword argument 'isSpeechBeepCommand'
IO - inputCore.executeGesture (10:45:03.187) - winInputHook (8284):
Input: kb(laptop):control+shift+NVDA+f1
```

**Comment by tmthywynn8** [comment]
Fixed in 37452d374f8e60a9e957b790abb1cc149af826c6.
